"""Model adapter: loads only project-generated artifacts from MODEL_DIR, verifies the manifest, scores vectors.

Failure to load yields a visible degraded (rules-only) state; it never blocks the deterministic path.
"""
from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

from app.detection.preprocess import anomaly_scores, domain_of
from app.features.vector import FEATURE_NAMES, FEATURE_VERSION

log = logging.getLogger("logorder.model")


@dataclass
class LoadedModel:
    model_id: str
    estimator: Any
    threshold: float
    feature_names: tuple[str, ...]
    calibration_scores: np.ndarray  # sorted ascending
    manifest: dict[str, Any]
    artifact_sha256: str

    def score(self, vector: list[float]) -> float:
        return float(anomaly_scores(self.estimator, vector)[0])  # higher = more anomalous; includes blind-spot penalty

    def percentile(self, score: float) -> float:
        """Empirical rarity percentile against the calibration distribution (never a probability of attack)."""
        n = len(self.calibration_scores)
        if n == 0:
            return float("nan")
        return float(np.searchsorted(self.calibration_scores, score, side="right") / n * 100.0)


class ModelLoadError(RuntimeError):
    pass


def _verify_preprocessing(est: Any, manifest: dict[str, Any]) -> None:
    """A domain pipeline must be fitted on the code's feature schema and match what the manifest claims."""
    dom = domain_of(est)
    declared = manifest.get("preprocessing")
    if dom is None:
        if declared:
            raise ModelLoadError("manifest declares preprocessing but the artifact carries none")
        return
    if tuple(dom.feature_names_in_) != FEATURE_NAMES:
        raise ModelLoadError("preprocessing stage was fitted on a different feature schema")
    if not declared or list(declared.get("forest_features", ())) != list(dom.kept_names):
        raise ModelLoadError("preprocessing stage does not match the manifest")


def sha256_path(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as fh:
        while chunk := fh.read(1 << 20):
            h.update(chunk)
    return h.hexdigest()


def load_model(model_dir: str | Path, model_id: str, expected_sha256: str | None = None, expected_reference_hash: str | None = None) -> LoadedModel:
    root = Path(model_dir).resolve()
    d = (root / model_id).resolve()
    if root not in d.parents:
        raise ModelLoadError("model id escapes MODEL_DIR")
    manifest_path = d / "manifest.json"
    if not manifest_path.exists():
        raise ModelLoadError(f"manifest missing for {model_id}")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("generator") != "logorder.ml.train":
        raise ModelLoadError("artifact was not generated by this project")
    if manifest.get("feature_version") != FEATURE_VERSION or tuple(manifest.get("feature_names", ())) != FEATURE_NAMES:
        raise ModelLoadError("feature schema mismatch between artifact and code")
    art = d / manifest["artifact_file"]
    digest = sha256_path(art)
    if digest != manifest["artifact_sha256"] or (expected_sha256 and digest != expected_sha256):
        raise ModelLoadError("artifact hash mismatch")
    if expected_reference_hash and manifest.get("reference_hash") != expected_reference_hash:
        raise ModelLoadError("model was trained against a different familiarity reference")
    import joblib
    import sklearn

    if manifest.get("dependencies", {}).get("scikit-learn") != sklearn.__version__:
        raise ModelLoadError(f"scikit-learn version mismatch: artifact {manifest.get('dependencies', {}).get('scikit-learn')} vs runtime {sklearn.__version__}")
    est = joblib.load(art)
    _verify_preprocessing(est, manifest)
    cal = np.asarray(json.loads((d / manifest["calibration_scores_file"]).read_text(encoding="utf-8")), dtype=float)
    cal.sort()
    if manifest.get("threshold") is None:
        raise ModelLoadError("artifact has no calibrated threshold")
    return LoadedModel(model_id=model_id, estimator=est, threshold=float(manifest["threshold"]), feature_names=FEATURE_NAMES,
                       calibration_scores=cal, manifest=manifest, artifact_sha256=digest)
